name: Run Tests

on:
  push:
    branches: "main" # Adjust the branch if needed
  pull_request:
    branches: "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Adjust as needed

      - name: Run tests
        run: python -m unittest # Adjust if needed
